[project]
name = "ai-dev-team"
version = "0.1.0"
description = "AI agent team for developing software projects"
channels = ["conda-forge", "pytorch"]
platforms = ["osx-arm64"]
readme = "README.md"

[dependencies]
python = ">=3.12,<3.13"
requests = "*"
pygit2 = "*"
psutil = "*"
pydantic = "*"
pytorch = "*"
torchvision = "*"

[tool.pixi.pypi-dependencies]
redis = "*"

[environments]
default = { solve-group = "default" }
test = {features =["test"], solve-group = "default" }
dev = {features=["dev"], solve-group = "default"}
prod = {features=["dev", "test"], solve-group = "default"}

[feature.test.dependencies]
pytest = "*"
coverage = "*"

[feature.dev.dependencies]
ruff = "*"
isort = "*"
mypy = "*"

[feature.test.tasks]
test = "pytest"

[tasks]
start = "python src/main.py"
